# Generated by Django 5.2.3 on 2025-06-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SMSA.facultad')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='uab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SMSA.unidadacademica'),
        ),
    ]
