# Generated by Django 5.2.3 on 2025-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0002_unidadacademica_asignatura_uab'),
    ]

    operations = [
        migrations.AddField(
            model_name='planestudio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='tipo_nivel',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
