# Generated by Django 5.2.3 on 2025-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0003_planestudio_activo_planestudio_tipo_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturaplan',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
