# Generated by Django 5.2.3 on 2025-06-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0004_asignaturaplan_fecha_modificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellidos',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombres',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='convocatoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='victima_conflicto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
