# Generated by Django 5.2.3 on 2025-06-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0005_rename_apellidos_estudiante_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='matricula_periodo_activo',
            field=models.CharField(blank=True, default='SI', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='victima_conflicto',
            field=models.CharField(blank=True, default='SI', max_length=10, null=True),
        ),
    ]
