# Generated by Django 5.2.3 on 2025-06-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0007_remove_estudiante_nombre_estudiante_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estudiante_riesgo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
