# Generated by Django 5.2.3 on 2025-06-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0008_estudiante_estudiante_riesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
