# Generated by Django 5.2.3 on 2025-06-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0009_asignatura_descripcion_planestudio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturaplan',
            name='carga_masiva',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
