# Generated by Django 5.2.3 on 2025-07-01 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0010_asignaturaplan_carga_masiva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignaturaplan',
            old_name='carga_masiva',
            new_name='parametrizacion',
        ),
    ]
