# Generated by Django 5.2.3 on 2025-07-01 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0011_rename_carga_masiva_asignaturaplan_parametrizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturaplan',
            name='plan_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SMSA.planestudio'),
        ),
    ]
