# Generated by Django 5.2.3 on 2025-07-01 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0012_alter_asignaturaplan_plan_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='parametrizacion',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignaturaplan',
            name='plan_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMSA.planestudio'),
        ),
    ]
