# Generated by Django 5.2.3 on 2025-07-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0013_asignatura_parametrizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='periodo_modificacion',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
