# Generated by Django 5.2.3 on 2025-07-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0015_periodo_sede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='periodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialacademico',
            name='periodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='matricula_periodo_activo',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.DeleteModel(
            name='Periodo',
        ),
    ]
