# Generated by Django 5.2.3 on 2025-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0016_alter_asignatura_periodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='periodo',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
