# Generated by Django 5.2.3 on 2025-08-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0017_remove_asignatura_periodo_asignatura_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
