# Generated by Django 5.2.3 on 2025-08-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSA', '0018_alter_asignatura_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturaplan',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='asignaturaplan',
            name='parametrizacion',
        ),
        migrations.AddField(
            model_name='user',
            name='dependencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
